networks:
  traefik:
    name: traefik
    external: true

services:
  hsr-puzzle-prod:
    image: ghcr.io/yukioru/puzzle/hsr-puzzle:prod-latest
    container_name: hsr-puzzle-prod
    restart: always
    networks:
      - traefik
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.hsr-puzzle-prod.rule=Host(`puzzle.yukio.ru`)
      - traefik.http.routers.hsr-puzzle-prod.middlewares=gzip@file,hsts@file
      - traefik.http.routers.hsr-puzzle-prod.entrypoints=websecure
      - traefik.http.routers.hsr-puzzle-prod.service=hsr-puzzle-prod
      - traefik.http.routers.hsr-puzzle-prod.tls=true
      - traefik.http.routers.hsr-puzzle-prod.tls.certresolver=letsencrypt
      - traefik.http.routers.hsr-puzzle-prod.tls.domains[0].main=yukio.ru
      - traefik.http.routers.hsr-puzzle-prod.tls.domains[0].sans=*.yukio.ru
      - traefik.http.services.hsr-puzzle-prod.loadbalancer.server.port=3000

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower-hsr-puzzle-prod
    restart: always
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 600 hsr-puzzle-prod