import type { Metadata } from "next";
import type { PropsWithChildren } from "react";
import { Geologica } from "next/font/google";
import "./globals.css";

import styles from './layout.module.css';

const geologica = Geologica({
  variable: "--font-geologica",
  subsets: ["latin", "cyrillic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  robots: {
    index: false,
    follow: false,
    googleBot: {
      index: false,
      follow: false,
      noimageindex: true,
      'max-video-preview': -1,
      'max-image-preview': 'none',
      'max-snippet': -1,
    },
  },
};

export default function RootLayout({ children }: Readonly<PropsWithChildren>) {
  return (
    <html lang="ru" className={geologica.variable}>
      <body>
        <main className={styles.base}>
          {children}
        </main>
      </body>
    </html>
  );
}
