import type { Metadata } from "next";
import type { PropsWithChildren } from "react";
import localFont from "next/font/local";
import "./globals.css";

import styles from './layout.module.css';

const honkai = localFont({
  variable: "--font-honkai",
  src: [
    {
      path: '../assets/fonts/medium.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../assets/fonts/bold.woff2',
      weight: '700',
      style: 'normal',
    }
  ],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  robots: {
    index: false,
    follow: false,
    googleBot: {
      index: false,
      follow: false,
      noimageindex: true,
      'max-video-preview': -1,
      'max-image-preview': 'none',
      'max-snippet': -1,
    },
  },
};

export default function RootLayout({ children }: Readonly<PropsWithChildren>) {
  return (
    <html lang="ru" className={honkai.variable}>
      <body>
        <main className={styles.base}>
          {children}
        </main>
      </body>
    </html>
  );
}
