name: Build and Push Docker Images

on:
  push:
    branches:
      - dev
      - prod

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set variables
        id: vars
        run: |
          TIMESTAMP=$(date +'%Y%m%d-%H%M%S')

          if [[ "${GITHUB_REF_NAME}" == "dev" ]]; then
            echo "TAG_LATEST=dev-latest" >> $GITHUB_ENV
            echo "TAG_TIME=dev-${TIMESTAMP}" >> $GITHUB_ENV
            echo "DOCKERFILE=docker/development/Dockerfile" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF_NAME}" == "prod" ]]; then
            echo "TAG_LATEST=prod-latest" >> $GITHUB_ENV
            echo "TAG_TIME=prod-${TIMESTAMP}" >> $GITHUB_ENV
            echo "DOCKERFILE=docker/production/Dockerfile" >> $GITHUB_ENV
          fi

          echo "IMAGE_BASE=ghcr.io/${GITHUB_REPOSITORY}/hsr-puzzle" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build \
            -f $DOCKERFILE \
            -t $IMAGE_BASE:$TAG_LATEST \
            -t $IMAGE_BASE:$TAG_TIME \
            .

      - name: Push Docker image
        run: |
          docker push $IMAGE_BASE:$TAG_LATEST
          docker push $IMAGE_BASE:$TAG_TIME
